# Generated by Django 5.0 on 2024-01-25 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=3000)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Norte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=3000)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=3000)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvatarImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
