# Generated by Django 5.0 on 2024-01-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=3000)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Norte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=3000)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=3000)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
